# -*- coding: utf-8 -*-
{
    'name': 'Exit Light Deliver Multiple Warehouses',
    'summary':
        '''
        Stop picking creation for orders on confirm,generated by Amazon or
        ecommerce site. Addition for details in forecast pop-up.
        ''',
    'description':
        '''
        Task id: 2657351.
        Stop picking creation for orders on confirm,generated by Amazon or 
        ecommerce site. Addition for details in forecast pop-up.
        ''',
    'author': "Odoo PS",
    'version': '15.0.1.0.0',
    'license': 'OEEL-1',
    'depends': [
        'purchase',
        'sale_management',
        'stock',
        'sale_amazon',
        'website_sale',
        'sale_stock'
    ],
    'data': [
        'views/delivery_views.xml',
        'views/sale_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'exit_light_deliver_multiple_warehouses/static/src/js/qty_at_date_widget_inherit.js',
        ],
        'web.assets_qweb': [
            'exit_light_deliver_multiple_warehouses/static/src/xml/**/*',
        ],
    }
}
